# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CloudCamera' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CloudCamera
	pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'
    pod 'AlamofireImage', '~> 3.5'
    pod 'IQKeyboardManagerSwift'
    
  target 'CloudCameraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CloudCameraUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
